export default {
  'add-line': '\ue839',
  'home-smile-2-line': '\ue6ba',
  'home-smile-2-fill': '\ue6b9',
  'user-5-line': '\ue889',
  'user-5-fill': '\ue88a',
  'checkbox-blank-circle-fill': '\ue848',
  'checkbox-blank-fill': '\ue849',
  'loader-5-line': '\ue85e',
  'image-2-fill': '\ue805',
  'arrow-down-s-line': '\ue83d',
  'arrow-left-s-line': '\ue842',
  'arrow-right-s-line': '\ue844',
  'check-line': '\ue847',
  'close-circle-fill': '\ue84a',
  'close-line': '\ue84b',
  'error-warning-fill': '\ue853',
  'arrow-up-s-line': '\ue857',
  'search-line': '\ue86e',
  'subtract-line': '\ue87b',
  'empty-data': '\ue632',
  'empty-search': '\ue634',
}

